package ru.elixor.api.exceptions.errors

class RecordInUseException : Exception()